# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Abramowicz\Tidio\Domain\Strategy\SalaryStrategy:
            tags: ['app.salary_strategy']

    Abramowicz\Tidio\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    Abramowicz\Tidio\Application\GenerateReport:
        arguments:
            $salaryStrategies: !tagged_iterator 'app.salary_strategy'

    Abramowicz\Tidio\Ui\Controller\:
        resource: '../src/Ui/Controller/'
        tags: ['controller.service_arguments']
